# Generated by Django 4.2.4 on 2023-08-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_remove_profile_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('next_steps', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('use_case', models.CharField(max_length=256)),
                ('how_to_use', models.CharField(max_length=256)),
                ('side_effects', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='hours',
        ),
        migrations.AddField(
            model_name='treatment',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='treatment',
            name='times',
            field=models.TextField(default=''),
        ),
    ]
