# Generated by Django 4.2.4 on 2023-08-26 16:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_treatment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='duration',
            field=models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(limit_value=100)]),
        ),
        migrations.AddField(
            model_name='treatment',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 16, 24, 44, 455919, tzinfo=datetime.timezone.utc)),
        ),
    ]
