# Generated by Django 4.2.4 on 2023-08-26 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_treatment_duration_treatment_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 16, 37, 45, 912051, tzinfo=datetime.timezone.utc)),
        ),
    ]
