# Generated by Django 4.2.4 on 2023-08-26 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_alter_profile_user_alter_treatment_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 18, 34, 8, 374592, tzinfo=datetime.timezone.utc)),
        ),
    ]
